---
title: Applicability
output: 
    html_document:
        css: styles.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#### The uses of ANNs are far reaching and interdisciplinary
Using **artificial neural networks**, we can greatly reduce the time spent on having
radiologists identify between benign and malignant microcalcifications and with
better accuracy regarding early detection of breast cancer in mammograms.  This,
of course, is applicable to other fields of medical science as well and is not
contained only to cancer research ([paper](http://downloads.hindawi.com/journals/cmmm/2017/2610628.pdf))

#### Facial recognition
**Artificial neural networks** can also aid in facial recognition using the same
process that we have on a much larger scale, although it can be limited by the
amount of enrolled users in the database that you are matching with ([paper](https://www.researchgate.net/publication/258312237_Face_Recognition_Using_Artificial_Neural_Networks))

#### Object detection
**Neural networks** can further be applied to not just 2D images, but also to real
life objects for collision avoidance and obstacle detection when designing self-
driving vehicles ([article](https://towardsdatascience.com/capsule-neural-networks-the-future-for-autonomous-vehicles-f97bc3f7918))

### Robotics
We can also use this to better sort recyclables instead of relying
on human eye detection.  The speed of which recyclables are sorted can also
increase with the implementation of the **convolutional neural network**, which we
mentioned was better suited to image recognition than an artificial neural
network ([article](https://towardsdatascience.com/how-to-build-an-image-classifier-for-waste-sorting-6d11d3c9c478), [paper](https://www.researchgate.net/publication/325626219_RecycleNet_Intelligent_Waste_Sorting_Using_Deep_Neural_Networks)).
